# Generated by Django 5.1.7 on 2025-05-10 03:54

import apps.usuario.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='usuario',
            managers=[
                ('objects', apps.usuario.models.UsuarioManager()),
            ],
        ),
    ]
